services:
  velib-lakehouse:
    build: .
    container_name: velib-lakehouse
    expose:
      - "4000"
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      S3_ENDPOINT_URL: '${S3_ENDPOINT_URL}'
      BUCKET: '${BUCKET}'
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    networks:
      - coolify
    restart: always

networks:
  coolify:
    external: true
    name: coolify

volumes:
  dagster_home:
    external: true
    name: dagster-workspace_dagster_home